# FireLead Project Demo

This notebook demonstrates the main features of the FireLead project, showcasing both the Firecrawl extraction and enhanced extraction capabilities.

## Setup and Imports

In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from extractor import FirecrawlDataExtractor
from data_saver import DataSaver
import json

# Load environment variables
load_dotenv()

# Get API key from environment variable
FIRECRAWL_API_KEY = os.getenv('FIRECRAWL_API_KEY')
if not FIRECRAWL_API_KEY:
    raise ValueError("FIRECRAWL_API_KEY environment variable is not set")

# Initialize extractor and data saver
extractor = FirecrawlDataExtractor(api_key=FIRECRAWL_API_KEY)
data_saver = DataSaver('data')

## 1. Basic Firecrawl Extraction

This section demonstrates the basic Firecrawl extraction functionality, which allows you to extract leads from various sources using a natural language prompt.

In [2]:
# Define the prompt and fields to extract
prompt = "Find companies in the AI/ML space that have raised funding in the last 6 months"

# Define which fields we want to extract
selected_fields = {
    "company_name": True,
    "funding": True,
    "industry": True,
    "description": True,
    "website_url": True,
    "email": True
}

# Define URL patterns to search
url_patterns = [
    "https://firecrawl.dev/*",
    "https://tracxn.com/*",
    "https://www.cbinsights.com/*",
    "https://pitchbook.com/*",
    "https://www.crunchbase.com/*"
]

print("Starting Firecrawl extraction...")
results = extractor.extract_leads(url_patterns, prompt, selected_fields, enable_web_search=True)

if results and 'data' in results and 'leads' in results['data']:
    # Convert to DataFrame
    df = pd.DataFrame(results['data']['leads'])
    print(f"\nFound {len(df)} leads")
    print("\nSample of extracted data:")
    display(df.head())

    # Save the results
    saved_file = data_saver.save(df)
    print(f"\nData saved to: {saved_file.name}")
else:
    print("No leads found in the extraction results")

Starting Firecrawl extraction...
{'company_name': 'str', 'funding': 'str', 'industry': 'str', 'description': 'str', 'website_url': 'str', 'email': 'str'}

model classes is builded
{'$defs': {'LeadModel': {'properties': {'company_name': {'title': 'Company Name', 'type': 'string'}, 'funding': {'title': 'Funding', 'type': 'string'}, 'industry': {'title': 'Industry', 'type': 'string'}, 'description': {'title': 'Description', 'type': 'string'}, 'website_url': {'title': 'Website Url', 'type': 'string'}, 'email': {'title': 'Email', 'type': 'string'}}, 'required': ['company_name', 'funding', 'industry', 'description', 'website_url', 'email'], 'title': 'LeadModel', 'type': 'object'}}, 'properties': {'leads': {'items': {'$ref': '#/$defs/LeadModel'}, 'title': 'Leads', 'type': 'array'}}, 'required': ['leads'], 'title': 'ExtractSchema', 'type': 'object'}
going for data
done for data

Found 554 leads

Sample of extracted data:

,email,funding,industry,description,website_url,company_name
0,,$7M,"General Advertising, Artificial Intelligence",AI big data analytics and...,,Vpon
1,,$7M,Artificial Intelligence,Company simplifying digit...,,Beacon
2,,$900K,Artificial Intelligence,Geospatial analytics vent...,,Ocean Ledger
3,,$5M,Artificial Intelligence,AI-driven platform transf...,,Outmarket AI
4,,$552K,Artificial Intelligence,AI tool recording multili...,,The Plato

✅ Data saved to: data\2025-04-10_17-32_leads.xlsx

Data saved to: 2025-04-10_17-32_leads.xlsx

## 2. Enhanced Extraction

This section demonstrates the enhanced extraction feature, which allows for more customized field extraction with specific data types.

In [9]:
# Define a more specific prompt
enhanced_prompt = "Find out the founder and CEO of the company, the year it was founded, and the number of employees. Also, check if they have a free trial available and what their target market is. Provide key features of the product as well."
url_patterns = ["https://unimans.com/", "https://www.brainguru.in/", "https://www.saasworthy.com/"]
# Define specific fields with their types
specific_fields = {
    "company_name": "str",
    "product_name": "str",
    "founding_year": "str",
    "ceo_name": "str",
    "number_of_employees": "number",
    "free_trial_available": "bool",
    "target_market": "str",
}

print("Starting enhanced extraction...")
enhanced_results = extractor.extract_leads_enhanced(
    url_patterns,
    enhanced_prompt,
    specific_fields,
    enable_web_search=True
)
print(enhanced_results)

if enhanced_results and 'data' in enhanced_results and 'leads' in enhanced_results['data']:
    # Convert to DataFrame
    enhanced_df = pd.DataFrame(enhanced_results['data']['leads'])
    print(f"\nFound {len(enhanced_df)} leads")
    print("\nSample of enhanced extraction data:")
    display(enhanced_df.head())

    # Save the results
    saved_file = data_saver.save(enhanced_df)
    print(f"\nData saved to: {saved_file.name}")
else:
    print("No leads found in the enhanced extraction results")

Starting enhanced extraction...
Building model with fields: {'company_name': 'str', 'product_name': 'str', 'founding_year': 'str', 'ceo_name': 'str', 'number_of_employees': 'float', 'free_trial_available': 'bool', 'target_market': 'str'}
model classes is builded
Schema: {'$defs': {'LeadModel': {'properties': {'company_name': {'title': 'Company Name', 'type': 'string'}, 'product_name': {'title': 'Product Name', 'type': 'string'}, 'founding_year': {'title': 'Founding Year', 'type': 'string'}, 'ceo_name': {'title': 'Ceo Name', 'type': 'string'}, 'number_of_employees': {'title': 'Number Of Employees', 'type': 'number'}, 'free_trial_available': {'title': 'Free Trial Available', 'type': 'boolean'}, 'target_market': {'title': 'Target Market', 'type': 'string'}}, 'required': ['company_name', 'product_name', 'founding_year', 'ceo_name', 'number_of_employees', 'free_trial_available', 'target_market'], 'title': 'LeadModel', 'type': 'object'}}, 'properties': {'leads': {'items': {'$ref': '#/$defs/LeadModel'}, 'title': 'Leads', 'type': 'array'}}, 'required': ['leads'], 'title': 'ExtractSchema', 'type': 'object'}
Extracting data with prompt: Find out the founder and CEO of the company, the year it was founded, and the number of employees. Also, check if they have a free trial available and what their target market is. Provide key features of the product as well.
Data extraction completed
{'success': True, 'data': {'leads': []}, 'status': 'completed', 'expiresAt': '2025-04-10T18:43:49.000Z'}

Found 0 leads

Sample of enhanced extraction data:

Empty DataFrame
Columns: []
Index: []

✅ Data saved to: data\2025-04-10_18-13_leads.xlsx

Data saved to: 2025-04-10_18-13_leads.xlsx

## 3. Data Analysis and Visualization

This section demonstrates how to analyze and visualize the extracted data.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Load the most recent saved file
saved_files = list(Path('data').glob('*.xlsx'))
if saved_files:
    latest_file = max(saved_files, key=lambda x: x.stat().st_mtime)
    df = pd.read_excel(latest_file)

    # Basic statistics
    print("Basic Statistics:")
    print(f"Total leads: {len(df)}")

    # If we have numeric columns, show their distribution
    numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
    if len(numeric_cols) > 0:
        print("\nNumeric columns distribution:")
        display(df[numeric_cols].describe())

        # Plot distributions
        for col in numeric_cols:
            plt.figure(figsize=(10, 4))
            sns.histplot(data=df, x=col)
            plt.title(f'Distribution of {col}')
            plt.show()

    # If we have categorical columns, show their value counts
    categorical_cols = df.select_dtypes(include=['object']).columns
    if len(categorical_cols) > 0:
        print("\nTop values in categorical columns:")
        for col in categorical_cols:
            print(f"\n{col}:")
            display(df[col].value_counts().head(10))

            # Plot top categories
            plt.figure(figsize=(10, 4))
            df[col].value_counts().head(10).plot(kind='bar')
            plt.title(f'Top 10 values in {col}')
            plt.xticks(rotation=45)
            plt.show()
else:
    print("No saved data files found")

## 4. Exporting Data

This section shows how to export the extracted data to different formats.

In [ ]:
# Load the most recent saved file
saved_files = list(Path('data').glob('*.xlsx'))
if saved_files:
    latest_file = max(saved_files, key=lambda x: x.stat().st_mtime)
    df = pd.read_excel(latest_file)

    # Export to different formats
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

    # CSV
    csv_file = f'data/leads_{timestamp}.csv'
    df.to_csv(csv_file, index=False)
    print(f"Data exported to CSV: {csv_file}")

    # JSON
    json_file = f'data/leads_{timestamp}.json'
    df.to_json(json_file, orient='records', indent=2)
    print(f"Data exported to JSON: {json_file}")

    # Excel (already saved)
    print(f"Data already saved as Excel: {latest_file.name}")
else:
    print("No saved data files found")